version: 2

updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0  # only allow security updates
    reviewers: ["valispace/automations"]
    labels: ["github-actions"]
    commit-message:
      prefix: "ci(workflows)"
    ignore:
      - update-types: ["version-update:semver-major"]

  # Maintain dependencies for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0  # only allow security updates
    reviewers: ["valispace/operations"]
    labels: ["docker"]
    commit-message:
      prefix: "build(docker)"
    ignore:
      - update-types: ["version-update:semver-major"]

  # Maintain dependencies for Python
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 0  # only allow security updates
    reviewers: ["valispace/fn"]
    labels: ["dependencies", "python"]
    commit-message:
      prefix: "build(pip)"
    ignore:
      - update-types: ["version-update:semver-major"]
      - dependency-name: "pylint"
        versions: [">2.x"]  # cannot update further without breaking integration with pylint-django-2.5.3
      - dependency-name: "pyparsing"
        versions: [">2.x"]  # cannot update further without breaking integration with pint-0.21.dev0+valispace
